2025-03-28 13:26:33,649 - root - INFO - 神奇九转策略启动
2025-03-28 13:26:33,912 - tiger_openapi - INFO - sdk version: 3.3.3
2025-03-28 13:26:34,172 - tiger_openapi - INFO - Backing off do_post(...) for 1.0s (tigeropen.common.exceptions.ResponseException: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='})
2025-03-28 13:26:35,232 - tiger_openapi - INFO - Backing off do_post(...) for 1.0s (tigeropen.common.exceptions.ResponseException: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='})
2025-03-28 13:26:36,282 - tiger_openapi - INFO - Backing off do_post(...) for 2.0s (tigeropen.common.exceptions.ResponseException: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='})
2025-03-28 13:26:38,332 - tiger_openapi - INFO - Backing off do_post(...) for 3.0s (tigeropen.common.exceptions.ResponseException: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='})
2025-03-28 13:26:41,383 - tiger_openapi - ERROR - Giving up do_post(...) after 5 tries (tigeropen.common.exceptions.ResponseException: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='})
2025-03-28 13:26:41,383 - tiger_openapi - ERROR - give up after 5 retries
2025-03-28 13:26:41,383 - tiger_openapi - ERROR - [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='}
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\quote\quote_client.py", line 114, in __fetch_data
    response = super(QuoteClient, self).execute(request, url=self._url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\tiger_open_client.py", line 186, in execute
    response = retry_deco(do_post)(url, query_string, self.__headers, params, self.__config.timeout,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\common\util\web_utils.py", line 17, in do_post
    return do_request('POST', url=url, query_string=query_string, headers=headers, params=params, timeout=timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\common\util\web_utils.py", line 36, in do_request
    raise ResponseException('[' + THREAD_LOCAL.uuid + ']invalid http status ' + str(response.status) +
tigeropen.common.exceptions.ResponseException: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='}
2025-03-28 13:26:41,390 - src.data_fetcher - ERROR - 初始化老虎证券API客户端失败: [36654090-0b95-11f0-acb8-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:26:33', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'T6Lr8G//BR4NuTJmgSHWANrDVtyn6JB2PPRLRLc9MVPymbKrshM28g3ZxAkrVhbYypKlYYxW4Mk6ZfSi1WZ4pEMkPmGwYLTlWiiaW0oGJ1lsBQVfH9tQVZTOaLYeKqyhyXioB5+DT9iYXIMrC9WYxridD7RQkRBieJj8/ZaNVXs='}
2025-03-28 13:26:41,391 - src.data_fetcher - WARNING - API客户端未初始化，使用测试数据
2025-03-28 13:26:41,391 - src.data_fetcher - WARNING - 生成 QQQ 的测试数据
2025-03-28 13:26:41,456 - src.data_fetcher - INFO - 测试数据已生成并缓存到: data/cache/QQQ_1m_2025-02-26_2025-03-28_mock.csv
2025-03-28 13:26:41,576 - root - INFO - 添加数据源: QQQ, 文件: data/cache/QQQ_1m_bt.csv
2025-03-28 13:26:41,577 - src.data_fetcher - WARNING - API客户端未初始化，使用测试数据
2025-03-28 13:26:41,577 - src.data_fetcher - WARNING - 生成 SPY 的测试数据
2025-03-28 13:26:41,659 - src.data_fetcher - INFO - 测试数据已生成并缓存到: data/cache/SPY_1m_2025-02-26_2025-03-28_mock.csv
2025-03-28 13:26:41,741 - root - INFO - 添加数据源: SPY, 文件: data/cache/SPY_1m_bt.csv
2025-03-28 13:26:41,742 - root - INFO - 初始资金: 100000.00
2025-03-28 13:26:42,216 - root - ERROR - 回测过程中发生错误: Stochastic.__init__() got an unexpected keyword argument 'period1'
